# This workflow will do a clean install of node dependencies, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: build

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:
  repository_dispatch:
    types:
      - webhook

jobs:
  pre-job:
    name: Pre-job
    runs-on: ubuntu-latest

    steps:
    
      - uses: technote-space/auto-cancel-redundant-workflow@v1

      - name: Cancel redundant workflows
        run: echo "Cancel redundant workflows finished"

  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
      with:
        ref: 'main'
    - name: Use Node.js 16.x
      uses: actions/setup-node@v3
      with:
        node-version: '16'
        cache: 'npm'
    - name: Cache dependencies
      uses: actions/cache@v3
      with:
        path: ~/.npm
        key: npm-${{ hashFiles('package-lock.json') }}
        restore-keys: npm-
    - run: npm run style
    - run: npm ci
    - run: npm run test
    - run: npm run build
    - name: get-npm-version
      id: package-version
      uses: martinbeentjes/npm-get-version-action@main
    - uses: montudor/action-zip@v1
      with:
        args: zip -qq -r mercari-enhancement-suite-${{ steps.package-version.outputs.current-version}}.zip dist
    - uses: actions/upload-artifact@v3
      with:
        name: mercari-enhancement-suite-artifacts
        path: "*.zip"
    - if: github.ref == 'refs/heads/main'
      uses: stefanzweifel/git-auto-commit-action@v4

  deploy:
    needs: build
    runs-on: ubuntu-latest

    if: github.ref == 'refs/heads/main'
    steps:
    - uses: actions/checkout@v3
      with:
        ref: 'main'
    - uses: actions/download-artifact@v3
      with:
        name: mercari-enhancement-suite-artifacts
    - name: get-npm-version
      id: package-version
      uses: martinbeentjes/npm-get-version-action@main
    - uses: ncipollo/release-action@v1
      with:
        artifactErrorsFailBuild: true
        tag: v${{ steps.package-version.outputs.current-version}}
        artifacts: "*.zip"
        token: ${{ secrets.YOUR_GITHUB_TOKEN }}
        body: "This extension will need to be loaded unpacked in developer mode:


1. Download `mercari-enhancement-suite.zip` and extract the `dist` directory somewhere

2. Follow these instructions to load: https://developer.chrome.com/docs/extensions/mv3/getstarted/#unpacked


Will work on Microsoft Edge as well."
    - name: Webhook
      uses: joelwmale/webhook-action@master
      with:
        url: ${{ secrets.WEBHOOK_URL }}
        headers: '{"content-type": "application/x-www-form-urlencoded", "cache-control": "no-cache"}'
        body: '{"api_key":"${{ secrets.WEBHOOK_API }}", "format": "json", "id": "792387595", "keyword_value": "r-v${{ steps.package-version.outputs.current-version}}"}'