# This workflow will do a clean install of node dependencies, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: build

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [16.x]
        # See supported Node.js release schedule at https://nodejs.org/en/about/releases/

    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}
    - run: npm ci
    - run: npm run style
    - run: npm run test
    - run: npm run build --if-present
    - uses: montudor/action-zip@v1
      with:
        args: zip -qq -r mercari-enhancement-suite.zip dist
    - uses: ncipollo/release-action@v1
      with:
        allowUpdates: true
        tag: "change-me"
        artifacts: "*.zip"
        token: ${{ secrets.YOUR_GITHUB_TOKEN }}
        body: "This extension will need to be loaded unpacked in developer mode:


1. Download `mercari-enhancement-suite.zip` and extract the `dist` directory somewhere

2. Follow these instructions to load: https://developer.chrome.com/docs/extensions/mv3/getstarted/#unpacked


Will work on Microsoft Edge as well."
    - uses: stefanzweifel/git-auto-commit-action@v4
