name: build

on:
  workflow_run:
    workflows: ["tests"]
    types:
      - completed

concurrency:
  group: ${{ github.workflow }}-${{ github.head_ref || github.ref_name }} 
  cancel-in-progress: true

jobs:
  build:
    runs-on: ubuntu-latest

    if: github.event.workflow_run.conclusion == 'success'
    steps:
    - uses: actions/checkout@v3
      with:
        ref: 'main'
    - name: Use Node.js 16.x
      uses: actions/setup-node@v3
      with:
        node-version: '16'
        cache: 'npm'
    - name: Cache dependencies
      uses: actions/cache@v3
      with:
        path: ~/.npm
        key: npm-${{ hashFiles('package-lock.json') }}
        restore-keys: npm-
    - run: npm ci
    - run: npx yarn run build
    - name: get-npm-version
      id: package-version
      uses: martinbeentjes/npm-get-version-action@main
    - uses: montudor/action-zip@v1
      with:
        args: zip -qq -r mercari-enhancement-suite-${{ steps.package-version.outputs.current-version}}.zip dist
    - uses: actions/upload-artifact@v3
      with:
        name: mercari-enhancement-suite-artifacts
        path: "*.zip"