name: release

on:
  workflow_run:
    workflows: ["build"]
    types:
      - completed

concurrency:
  group: ${{ github.workflow }}-${{ github.head_ref || github.ref_name }} 
  cancel-in-progress: true

jobs:
  deploy:
    runs-on: ubuntu-latest
    outputs:
      version: ${{ steps.package-version.outputs.current-version }}
    if: github.ref == 'refs/heads/main' && github.event.workflow_run.conclusion == 'success'
    steps:
    - uses: actions/checkout@v4
      with:
        ref: 'main'
    - name: Download artifact
      uses: dawidd6/action-download-artifact@v2
      with:
        github_token: ${{ secrets.YOUR_GITHUB_TOKEN }}
        workflow: build.yml
        name: mercari-enhancement-suite-artifacts
    - name: get-npm-version
      id: package-version
      uses: martinbeentjes/npm-get-version-action@main
    - uses: ncipollo/release-action@v1
      with:
        artifactErrorsFailBuild: true
        tag: v${{ steps.package-version.outputs.current-version }}
        artifacts: "*.zip"
        token: ${{ secrets.YOUR_GITHUB_TOKEN }}
        body: |-
          "This extension will need to be loaded unpacked in developer mode:
          1. Download `mercari-enhancement-suite.zip` and extract the `dist` directory somewhere
          2. Follow these instructions to load: https://developer.chrome.com/docs/extensions/mv3/getstarted/#unpacked
          Will work on Microsoft Edge as well."
    - name: Slack Notify of Success
      uses: rtCamp/action-slack-notify@v2
      if: success()
      env:
        SLACK_WEBHOOK: ${{ secrets.SLACK_WEBHOOK }}
        SLACK_USERNAME: release-bot
        SLACK_COLOR: ${{ job.status}}
        SLACK_ICON: https://icons8.com/icon/sz8cPVwzLrMP/check-mark
        MSG_MINIMAL: true
        SLACK_MESSAGE:
          https://github.com/FableStitch/mercari-enhancement-suite/releases/download/v${{ steps.package-version.outputs.current-version }}/mercari-enhancement-suite-${{ steps.package-version.outputs.current-version }}.zip
    - name: Slack Notify of Failure
      uses: rtCamp/action-slack-notify@v2
      if: failure()
      env:
        SLACK_WEBHOOK: ${{ secrets.SLACK_WEBHOOK }}
        SLACK_USERNAME: release-bot
        SLACK_ICON: https://icons8.com/icon/T9nkeADgD3z6/cross-mark
        SLACK_COLOR: ${{ job.status}}
