name: tests

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:
  repository_dispatch:
    types:
      - webhook

concurrency:
  group: ${{ github.workflow }}-${{ github.head_ref || github.ref_name }} 
  cancel-in-progress: true

jobs:
  tests:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
      with:
        ref: 'main'
    - name: Use Node.js 16.x
      uses: actions/setup-node@v3
      with:
        node-version: '16'
        cache: 'npm'
    - name: Cache dependencies
      uses: actions/cache@v3
      with:
        path: ~/.npm
        key: npm-${{ hashFiles('package-lock.json') }}
        restore-keys: npm-
    - run: npm run style
    - run: npm ci
    - run: npm run test
    - if: github.ref == 'refs/heads/main'
      uses: stefanzweifel/git-auto-commit-action@v4