name: version-commit
on:
  workflow_run:
    workflows: ["version-check"]
    types:
      - completed
jobs:
  trigger-version-update:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: actions/github-script@v4
        id: get-artifact-id
        with:
          result-encoding: string
          script: |
            const result = await github.request('GET /repos/{owner}/{repo}/actions/runs/{run_id}/artifacts', {
              owner: '${{github.repository_owner}}',
              repo: '${{github.event.repository.name}}',
              run_id: ${{github.event.workflow_run.id}}
            })
            console.log(result)
            return result.data.artifacts[0].id
      - name: Get result
        run: |
          echo "${{steps.get-artifact-id.outputs.result}}"
          curl -L -H "Authorization: token ${{github.token}}" \
            -H "Accept: application/vnd.github.v3+json" \
            --output variables.zip \
            https://api.github.com/repos/${{github.repository}}/actions/artifacts/${{steps.get-artifact-id.outputs.result}}/zip
          unzip variables.zip
      - name: check if needed
        id: version-check
        run:
          echo "version=$(cat version.txt)" >> "$GITHUB_ENV"
      - name: no need to run
        if: env.version == 'PASS'
        run: exit 1
      - uses: actions/checkout@v4
      - name: Use Node.js 16.x
        uses: actions/setup-node@v3
        with:
          node-version: '16.20.1'
      - run: npm ci
      - name: npm run test
        run: npm run test
      - run: echo "version=$(cat version.txt)" >> "$GITHUB_ENV"
      - name: commit our changes
        uses: stefanzweifel/git-auto-commit-action@v4
        with:
          commit_message: "automatic update to ${{ env.version }}"
          commit_options: '--no-verify'
      - name: Slack Notify of Failure
        uses: rtCamp/action-slack-notify@v2
        if: failure() && env.version != 'PASS'
        env:
          SLACK_WEBHOOK: ${{ secrets.SLACK_WEBHOOK }}
          SLACK_USERNAME: release-bot
          SLACK_ICON_EMOJI: https://img.icons8.com/emoji/48/cross-mark-emoji.png
          SLACK_COLOR: ${{ job.status}}
          SLACK_MESSAGE: There is a new version of mercari-enhancement-suite but the tests failed. Check the logs!
